version: '3'
services:
  app:
    image: my-app:latest
    build:
        context: ./vendor/bin/sail
        dockerfile: Dockerfile
    networks:
      - my-network
    volumes:
      - my-volume:/app/data
    environment:
      - URL=mysql://username:password@db:3306/mydatabase
